name: first workflow

on: repository_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello Leon"
    - name: Print bye
      run: echo "bye Leon"

