name: first workflow

on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello Leon"
    - name: Print bye
      run: echo "bye Leon"
    - name: checkout
      uses: actions/checkout@v2.3.4
    - name: Install nodejs
      uses: actions/setup-node@v2.1.3
      with:
        node-version: 18
    - name: Install deps
      run: npm ci
    - name: run tests
      run: npm test


