name: first workflow

on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Print greeting
      run: echo "Hello Leon"
    - name: Print bye
      run: echo "bye Leon"
    - name: checkout
      uses: actions/checkout@v2.3.4
    - name: getcontexts
      run: echo "${{ toJSON(github) }}"


